In [1]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import f1_score
#Use different approaches here
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
import numpy as np
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
import nltk
#nltk.download('stopwords')
#nltk.download('punkt')
import re

#Use different approaches here
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
from keras.layers import Input, Dense
from keras.models import Model
from sklearn.model_selection import train_test_split
# from sklearn.multioutput import MultiOutputClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

import csv
import tensorflow as tf
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

Using TensorFlow backend.
C:\Users\sonur\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\sonur\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\sonur\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\sonur\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py

In [16]:
traindata = pd.read_csv("C:\\Users\\sonur\\Downloads\\DataScienceProject\\DBLPTrainset.txt", delimiter = '\t')
testdata = pd.read_csv("C:\\Users\\sonur\\Downloads\\DataScienceProject\\DBLPTestset.txt", delimiter = '\t')
groundtruthdata = pd.read_csv("C:\\Users\\sonur\\Downloads\\DataScienceProject\\DBLPTestGroundTruth.txt", delimiter = '\t')

path = "C:\\Users\\sonur\\Downloads\\DataScienceProject\\DBLPTrainset.txt" 
traindata = pd.read_table(path, header=None, names=['num', 'conference', 'papername'])

path = "C:\\Users\\sonur\\Downloads\\DataScienceProject\\DBLPTestset.txt" 
testdata = pd.read_table(path, header=None, names=['num','papername'])


path = "C:\\Users\\sonur\\Downloads\\DataScienceProject\\DBLPTestGroundTruth.txt" 
groundtruthdata = pd.read_table(path, header=None, names=['num','conference'])

C:\Users\sonur\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  
C:\Users\sonur\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  if __name__ == '__main__':
C:\Users\sonur\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  del sys.path[0]


In [17]:
traindata['label_conference'] = traindata.conference.map({'ISCAS':0, 'INFOCOM':1, 'VLDB':2, 'WWW':3, 'SIGGRAPH':4})
traindata

num conference                                          papername  \
0          0      ISCAS  Scalable Serial-parallel Multiplier over GF(2m...   
1          1   SIGGRAPH                                Plenoptic sampling.   
2          2      ISCAS  Sensitivity and uniformity of a 0.18micrometer...   
3          3        WWW      A survey of web archive search architectures.   
4          4      ISCAS  Understanding dynamic behavior of mm-wave CML ...   
5          5   SIGGRAPH  Cosine lobe based relighting from gradient ill...   
6          6    INFOCOM  Dimensioning an OBS Switch with Partial Wavele...   
7          7      ISCAS  A study of identifibility for blind source sep...   
8          8      ISCAS  A signal perturbation free semi-blind MRT MIMO...   
9          9      ISCAS  A low-power V-band CMOS low-noise amplifier us...   
10        10      ISCAS  Supply noise insensitive ring VCO with on-chip...   
11        11      ISCAS  A 3.3 &micro;W dual-modulus frequency divider ...   
12        12      ISCAS  A bio-inspired ultrasensitive imaging chip - P...   
13        13      ISCAS  Digit-serial/parallel multipliers with improve...   
14        14        WWW     Towards liquid service oriented architectures.   
15        15   SIGGRAPH  Adaptive importance sampling for multi-ray gat...   
16        16      ISCAS  Live demonstration: MWC for real-time applicat...   
17        17    INFOCOM  Routing and Wavelength Assignment in WDM Rings...   
18        18      ISCAS  Current mode multiple-valued adder for cryptog...   
19        19       VLDB        A Model for Integrated Information Systems.   
20        20   SIGGRAPH  Webbed Spaces: Between Exhibition and Network ...   
21        21        WWW   Comparative evaluation of javascript frameworks.   
22        22   SIGGRAPH                                  Infinite 4D fish.   
23        23       VLDB  StreamTX: extracting tuples from streaming XML...   
24        24      ISCAS  ASIP Decoder Architecture for Convolutional an...   
25        25       VLDB  Privacy-Preserving Indexing of Documents on th...   
26        26       VLDB  An Extendible Hash for Multi-Precision Similar...   
27        27      ISCAS  A motion compensation system with a high effic...   
28        28        WWW  Kairos: A Web-Based System for Automatic Gener...   
29        29      ISCAS  An On-Chip Delta-Time-to-Voltage Converter for...   
...      ...        ...                                                ...   
21613  21613      ISCAS  3D Oncological PET volume analysis using CNN a...   
21614  21614      ISCAS  A Vision-based People Counting Approach based ...   
21615  21615      ISCAS  Closed Form Parameters Estimation for Near Fie...   
21616  21616       VLDB    Unrolling Cycles to Decide Trigger Termination.   
21617  21617      ISCAS  A new type of microinverter for Photovoltaic p...   
21618  21618       VLDB                    Distributed Online Aggregation.   
21619  21619        WWW                 ViBE: virtual biology experiments.   
21620  21620       VLDB  Accommodating Exceptions in Databases, and Ref...   
21621  21621        WWW                 Applications of open search tools.   
21622  21622    INFOCOM  A Comparison of Media Synchronization Quality ...   
21623  21623        WWW  Using landing pages for sponsored search ad se...   
21624  21624    INFOCOM    Improving AS relationship inference using PoPs.   
21625  21625    INFOCOM  Simple Directional Antennas: Improving Perform...   
21626  21626    INFOCOM   TCP Sending Rate Control at Terabits Per Second.   
21627  21627    INFOCOM  Experimental evaluation of content distributio...   
21628  21628      ISCAS          Low Peak Power ATPG for n-Detection Test.   
21629  21629   SIGGRAPH  Applying color theory to creating scientific v...   
21630  21630       VLDB                Keyword-aware Optimal Route Search.   
21631  21631   SIGGRAPH  Universal capture: image-based facial animatio...   
21632  21632   SIGGRAPH  Integr

In [18]:
groundtruthdata.conference.value_counts()

ISCAS       2043
INFOCOM      502
WWW          423
VLDB         219
SIGGRAPH     186
Name: conference, dtype: int64

In [19]:
groundtruthdata['label_conference'] = groundtruthdata.conference.map({'ISCAS':0, 'INFOCOM':1, 'VLDB':2, 'WWW':3, 'SIGGRAPH':4})
groundtruthdata.head()

num conference  label_conference
0    0      ISCAS                 0
1    1      ISCAS                 0
2    2      ISCAS                 0
3    3        WWW                 3
4    4   SIGGRAPH                 4

In [20]:
X_train = traindata.papername
y_train = traindata.label_conference
print('finished')
print(X_train.shape)
print(y_train.shape)

finished
(21643,)
(21643,)


In [21]:
vect = CountVectorizer()
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)
X_train_dtm
print(X_train_dtm.shape[1])

14685


In [22]:
X_test = testdata.papername
y_test = groundtruthdata.label_conference
X_test_dtm = vect.transform(X_test)
X_test_dtm
print(X_test.shape)
print(y_test.shape)

(3373,)
(3373,)


In [23]:

#use final approach selected here
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train_dtm, y_train)
y_test_pred = nb.predict(X_test_dtm)
from sklearn import metrics
print(metrics.classification_report(y_test, y_test_pred))
print(metrics.accuracy_score(y_test,y_test_pred))
print(f1_score(y_test, y_test_pred, average='micro'))

results = confusion_matrix(y_test, y_test_pred)
print("Results MultinomialNB")
print('Confusion matrix using MultinomialNB: \n', results)


print("\nAccuracy: ", accuracy_score(y_test, y_test_pred)) # accuracy for multilabel
print("Precision: ",precision_score(y_test, y_test_pred, average='micro'))
print("Recall: ",recall_score(y_test, y_test_pred, average='micro'))

              precision    recall  f1-score   support

           0       0.97      0.92      0.94      2043
           1       0.74      0.79      0.77       502
           2       0.56      0.74      0.64       219
           3       0.77      0.77      0.77       423
           4       0.78      0.73      0.75       186

    accuracy                           0.86      3373
   macro avg       0.76      0.79      0.77      3373
weighted avg       0.87      0.86      0.86      3373

0.8612511117699377
0.8612511117699377
Results MultinomialNB
Confusion matrix using MultinomialNB: 
 [[1883   86   45    9   20]
 [  28  399   27   42    6]
 [   5   17  163   32    2]
 [   5   34   50  325    9]
 [  30    4    5   12  135]]

Accuracy:  0.8612511117699377
Precision:  0.8612511117699377
Recall:  0.8612511117699377


In [24]:

#Feature Extraction

from nltk.stem import WordNetLemmatizer
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.tokenize.treebank import TreebankWordDetokenizer
from nltk.corpus import stopwords

# 'The quick brown'
def Preprocessing(text):
    lemmatizer = WordNetLemmatizer()

    traindata_stop = []
    stopWords = set(stopwords.words('english'))
    wordsFiltered =[]
    wordsFiltered_complete = []

    from nltk.stem import PorterStemmer
    ps = PorterStemmer()


    for title in text:
        s = re.sub(r"[!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~]+\ *", " ", title) #remove punctuation
        #no_number = re.sub(r'\d+', '', s).lower()#remove numbers
        words = word_tokenize(s.lower())
        #result=[w for w in words if len(w) > 1] #remove single characters
        x = []
        for w in words:        
            a =lemmatizer.lemmatize(w)  #lemmatizer.lemmatize(w) #ps.stem(w) 
            if a not in stopWords:
                x.append(a)
            wordsFiltered = TreebankWordDetokenizer().detokenize(x)
        wordsFiltered_complete.append(wordsFiltered)

    text_processed = pd.DataFrame(wordsFiltered_complete, columns=['papername'])

    return text_processed.papername
    #print(X_train)

X_train=Preprocessing(X_train)
vect = CountVectorizer()
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

X_test=Preprocessing(X_test)
X_test_dtm = vect.transform(X_test)

In [25]:
X_train_dtm.shape[1]

13182

In [26]:
"""
With only Naive Bayes, the accuracy is 82 percent / 81 with some pre-processing
"""
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import Pipeline
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.decomposition import PCA

def NaiveBayes(X_train_dtm,y_train,X_test_dtm,y_test):
    text_clf = Pipeline([#('vect', CountVectorizer()),
                         ('tfidf', TfidfTransformer()),
#                         ('pca', PCA()),
                         ('clf', MultinomialNB()),
                         ])
    text_clf.fit(X_train_dtm, y_train)
    predicted = text_clf.predict(X_test_dtm)
    return predicted

predicted=NaiveBayes(X_train_dtm,y_train,X_test_dtm,y_test)
print(metrics.classification_report(y_test, predicted))
print(metrics.accuracy_score(predicted,y_test))
print(f1_score(y_test, predicted, average='micro'))


results = confusion_matrix(y_test, predicted)
print("Results MultinomialNB")
print('Confusion matrix using MultinomialNB: \n', results)

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      2043
           1       0.78      0.81      0.79       502
           2       0.62      0.72      0.67       219
           3       0.85      0.70      0.77       423
           4       0.93      0.59      0.72       186

    accuracy                           0.87      3373
   macro avg       0.82      0.76      0.78      3373
weighted avg       0.88      0.87      0.87      3373

0.8737029350726356
0.8737029350726356
Results MultinomialNB
Confusion matrix using MultinomialNB: 
 [[1979   41   20    1    2]
 [  53  406   19   21    3]
 [  18   19  158   23    1]
 [  28   46   52  295    2]
 [  55    8    6    8  109]]


In [27]:
"""
SVC gives an accuracy of 83.6, without tfidf, it gives 81.3 
->SVC gives an accuracy of 84.53 not preprocessed without tfidf, 82.9, preprocessed without tfidf, 
it gives 84.42 not preprocessed with tfid and  84.96 with tfidf preprocessed

Comment out the tf idf line in the pipeline to check this
"""


from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

# X_train = X_train_new
# X_test = X_test_new
# y_train = y_train
# y_test = y_test
def SVC(X_train_dtm,y_train,X_test_dtm,y_test):
    text_clf = Pipeline([#('vect', CountVectorizer()),
#                         ('tfidf', TfidfTransformer()),
                         ('clf', LinearSVC()),
                         ])
    text_clf.fit(X_train_dtm, y_train)
    predicted = text_clf.predict(X_test_dtm)
    return predicted

predicted=SVC(X_train_dtm,y_train,X_test_dtm,y_test)
print(metrics.classification_report(y_test, predicted))
print(metrics.accuracy_score(y_test, predicted))
print(f1_score(y_test, predicted, average='micro'))

results = confusion_matrix(y_test, predicted)
print("Results MultinomialNB")
print('Confusion matrix using MultinomialNB: \n', results)


              precision    recall  f1-score   support

           0       0.97      0.88      0.92      2043
           1       0.75      0.78      0.76       502
           2       0.51      0.75      0.60       219
           3       0.74      0.73      0.74       423
           4       0.59      0.78      0.67       186

    accuracy                           0.83      3373
   macro avg       0.71      0.79      0.74      3373
weighted avg       0.85      0.83      0.84      3373

0.832196857396976
0.832196857396976
Results MultinomialNB
Confusion matrix using MultinomialNB: 
 [[1795   96   57   31   64]
 [  31  392   32   33   14]
 [   6    9  164   33    7]
 [  12   25   59  310   17]
 [  16    2   12   10  146]]


In [30]:
from keras import Sequential
from keras.layers import Dense

def Sparse_matrix(y): #create sparse matrix for labels
    type_labels = list(set(y))
    label_vector=[]
    for i in y: 
        label_line=[]
        for l in type_labels:
            if l == i:
                label_line.append(1)
            else:
                label_line.append(0)
        label_vector.append(label_line)
    y_sparse=np.array(label_vector)
    return y_sparse

def DNN(X_train_dtm,y_train,X_test_dtm,y_test):

    input_dim = X_train_dtm.shape[1]
    y_train_sparse=Sparse_matrix(y_train)
    y_test_sparse=Sparse_matrix(y_test)


    NN_classifier = Sequential()
    #First Hidden Layer
    NN_classifier.add(Dense(10, activation='relu', kernel_initializer='random_normal', input_dim=input_dim)) #input number of vocabulary
    #Second  Hidden Layer
    NN_classifier.add(Dense(10, activation='relu', kernel_initializer='random_normal'))
    #Output Layer
    NN_classifier.add(Dense(5, activation='sigmoid', kernel_initializer='random_normal')) #output 5 classes
    #Compiling the neural network
    NN_classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['accuracy'])
    #Fitting the data to the training dataset
    NN_classifier.fit(X_train_dtm,y_train_sparse, batch_size=10, epochs=20)
    eval_model=NN_classifier.evaluate(X_train_dtm, y_train_sparse)
    eval_model
    
    y_tst_pred=NN_classifier.predict(X_test_dtm)
    y_tst_pred =(y_tst_pred>=0.5)
    return (y_test_sparse, y_tst_pred)

#print(y_tst_pred)
# y_test_sparse, y_tst_pred=DNN(X_train_dtm,y_train,X_test_dtm,y_test)
# print(metrics.classification_report(y_test_sparse, y_tst_pred))
# metrics.accuracy_score(y_tst_pred, y_test_sparse)

In [ ]:
from sklearn.model_selection import KFold # import KFold
from sklearn.feature_extraction.text import TfidfVectorizer

kf = KFold(n_splits=5) # Define the split - into 2 folds 
kf.get_n_splits(traindata) # returns the number of splitting iterations in the cross-validator
print(kf) 
NB_avg=0
SVC_avg=0
DNN_avg=0

for train_index, test_index in kf.split(traindata.papername):
    print('\nTRAIN:', train_index, 'TEST:', test_index)
    X_train0, X_test0 = traindata.papername[train_index], traindata.papername[test_index]
    y_train, y_test = traindata.label_conference[train_index], traindata.label_conference[test_index]   
    
    X_train=Preprocessing(X_train0)
    vect = TfidfVectorizer()
    vect.fit(X_train)
    X_train_dtm = vect.transform(X_train)

    X_test=Preprocessing(X_test0)
    X_test_dtm = vect.transform(X_test)
    
#     X_train_dtm,X_test_dtm=autoencoder(X_train_dtm,X_test_dtm)
    
#     predicted=NaiveBayes(X_train_dtm,y_train,X_test_dtm,y_test)
#     #print(metrics.classification_report(y_test, predicted))
#     precision=precision_score(predicted, y_test, average='micro')
#     recall=recall_score(predicted, y_test, average='micro')
#     f1=f1_score(predicted, y_test, average='micro')
#     print("Naive Bayes","\tPrecision: ",precision, "\trecall", recall, "\tf1", f1)
#     NB_avg=NB_avg+precision
        
#     predicted=SVC(X_train_dtm,y_train,X_test_dtm,y_test)
#     #print(metrics.classification_report(y_test, predicted))
#     precision=precision_score(predicted, y_test, average='micro')
#     recall=recall_score(predicted, y_test, average='micro')
#     f1=f1_score(predicted, y_test, average='micro')
#     print("SVC","\tPrecision: ",precision, "\trecall", recall, "\tf1", f1)
#     SVC_avg=SVC_avg+precision
    
    y_test_sparse, y_tst_pred=DNN(X_train_dtm,y_train,X_test_dtm,y_test)
    #print(metrics.classification_report(y_test, predicted))
    precision=precision_score(y_tst_pred, y_test_sparse, average='micro')
    recall=recall_score(y_tst_pred, y_test_sparse, average='micro')
    f1=f1_score(y_tst_pred, y_test_sparse, average='micro')
    print("DNN","\tPrecision: ",precision, "\trecall", recall, "\tf1", f1)
    DNN_avg=DNN_avg+precision

# print("NB_avg",NB_avg/5)    
# print("SVC_avg",SVC_avg/5)    
print("DNN_avg",DNN_avg/5)    


KFold(n_splits=5, random_state=None, shuffle=False)

TRAIN: [ 4329  4330  4331 ... 21640 21641 21642] TEST: [   0    1    2 ... 4326 4327 4328]
Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
Epoch 1/20
17314/17314 [==============================] - 4s 254us/step - loss: 0.4362 - accuracy: 0.83010s - l
Epoch 2/20
17314/17314 [==============================] - 5s 285us/step - loss: 0.2935 - accuracy: 0.8699
Epoch 3/20
17314/17314 [==============================] - 4s 237us/step - loss: 0.1873 - accuracy: 0.9114
Epoch 4/20
17314/17314 [==============================] - 4s 236us/step - loss: 0.1499 - accuracy: 0.9235
Epoch 5/20
17314/17314 [==============================] - 4s 238us/step - loss: 0.1300 - accuracy: 0.9398
Epoch 6/20
17314/17314 [==============================] - 4s 237us/step - loss: 0.1062 - accuracy: 0.9650
Epoch 7/20
17314/17314 [==============================] - 4s 257us/step - loss: 0.0779 - accur